### ISSUE TITLE
Nao aparece o resultado

### ISSUE THREAD

**Issue by pretorivm** [leonardomv1981/consulta-processo-judicial-apicnj#1]
Boa noite, primeiramente parabens pelo projeto, ficou muito top.
Quanto tento buscar um CNJ me traz erro abaixo fiz um var_dump para ver a saida.
Usei o exemplo do link https://datajud-wiki.cnj.jus.br/api-publica/exemplos/exemplo1

array (size=9)
  'numeroCNJ' => string '00008323520184013202' (length=20)
  'n' => string '0000832' (length=7)
  'd' => string '35' (length=2)
  'a' => string '2018' (length=4)
  'j' => string '4' (length=1)
  'tr' => int 1
  'o' => string '3202' (length=4)
  'api' => string 'https://api-publica.datajud.cnj.jus.br/api_publica_trf1/_search' (length=63)
  'nome_tribunal' => string 'Tribunal Regional Federal da 1a Região' (length=39)

Retorno do CURL
apicnjClass.php:224:boolean false

 'erro' => string 'Erro! Não foi possível encontrar dados do processo. Isso pode acontecer porque ele é sigiloso ou está tramitand
 
 Pode me ajudar

**Comment by leonardomv1981** [comment]
Oi Raimundo, bom dia.
Então, eu testei aqui com o número do processo que você mandou e funcionou
normal. Envio print anexo.
Talvez você tenha feito alguma alteração no código que ocasionou o
problema. Inclusive, não entendi o que você quis dizer com ter usado um
exemplo da api pública.
De qualquer forma, tente dar uma atualizada no repositório. Inclusive eu
fiz uma alteração hoje.
[image: Captura de Tela 2024-05-28 às 07.53.43.png]

Em seg., 27 de mai. de 2024 às 22:27, Raimundo Oliveira Junior <
***@***.***> escreveu:

**Comment by pretorivm** [comment]
Obrigado pelo retorno, estarei verificando.
